export default {
    "EMAIL_ERR": "EMAIL_ERR",
    "PASSWORD_ERR": "PASSWORD_ERR",
    "USER_ERR": "USER_ERR",
    "AUTH_ERR": "AUTH_ERR",
    "SERVER_ERR": "SERVER_ERR",
    "SUCCESS": "SUCCESS",
    "FAILED": "FAILED",
    "PRODUCT_NAME_ERR": "PRODUCT_NAME_ERR",
    "PRODUCT_DESC_ERR": "PRODUCT_DESC_ERR",
    "PRODUCT_PRICE_ERR": "PRODUCT_PRICE_ERR",
    "PRODUCT_IMAGES_ERR": "PRODUCT_IMAGES_ERR",
}